# Generated by Django 4.1.6 on 2023-02-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
