# Generated by Django 4.0.6 on 2023-02-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_phones'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('complete_name', models.CharField(max_length=20)),
                ('age', models.FloatField()),
            ],
        ),
    ]
