# Generated by Django 4.0.6 on 2023-02-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
