# Generated by Django 4.0.6 on 2023-02-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='email@example.com', max_length=254),
        ),
    ]
