# Generated by Django 4.0.6 on 2023-03-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='complete_name',
            field=models.CharField(max_length=254),
        ),
    ]
