# Generated by Django 4.0.6 on 2023-03-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_user_complete_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('complete_name', models.CharField(max_length=254)),
                ('email', models.EmailField(default='email@example.com', max_length=254)),
            ],
        ),
    ]
